spring:
  application:
    name: ToDoListService
    description: @project.description@
    version: @project.version@

server:
  port: 8080

#*********** Application health management configuration ********#
management:
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true
  endpoints:
    web:
      base-path: /management
      exposure:
        exclude: ["shutdown","startup"]
        include: "*"
  health:
    readinessstate:
      enabled: true

#*********** Springdoc OpenAPI configuration ***********************#
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
    groups-order: asc
  show-actuator: true