apiVersion: apps/v1
kind: Deployment
metadata:
  name: todolist-backend
  labels:
    app: todolist-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todolist-backend
  template:
    metadata:
      labels:
        app: todolist-backend
        version: risky
    spec:
      containers:
        - name: todolist-backend
          image: garbiozyildiz/todolist-backend:1.0.0-SNAPSHOT
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: todolist-backend
  labels:
    app: todolist-backend
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30007
      protocol: TCP
  selector:
    app: todolist-backend